### ISSUE TITLE
ExceptionInInitializerError trying to run

### ISSUE THREAD

**Issue by keithdtyler** [MajeurAndroid/Adb-Remote-Screen#10]
Getting this on both Java7 and Java 8.

Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.majeur.ars.AdbRemoteScreen.main(AdbRemoteScreen.java:13)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1911)
        at com.majeur.ars.Utils.getRunningJarPath(Utils.java:23)
        at com.majeur.ars.LocalProperties.<clinit>(LocalProperties.java:21)
        ... 1 more

**Comment by waterdaan** [comment]
try setting adb path in local.properties

**Comment by pete111** [comment]
I am getting the same error. I tried both in cmd line adb as well as in local.properties. None worked. I am on Win10. Log seems to work, but I am getting the same error and no picture is shown.

Phone reacts to buttons from jar app, but screen is not shown on pc.


log:
01:04:09.363	INFO: Adb path used: adb.exe
01:04:14.724	INFO: Connected devices changed
01:04:14.726	INFO: Start rendering device screen
01:04:19.756	INFO: Connected devices changed
01:04:19.757	INFO: Start rendering device screen
01:04:19.758	INFO: Stop rendering device screen
01:04:24.789	INFO: Connected devices changed
01:04:24.790	INFO: Stop rendering device screen
01:04:24.790	INFO: No device found
01:04:29.824	INFO: Connected devices changed
01:04:29.825	INFO: Start rendering device screen

UPDATE: On Ubuntu it works. But it is very very delayed even with limitFrameRate=False

**Comment by TobiX** [comment]
https://github.com/MajeurAndroid/Adb-Remote-Screen/blob/3f56fefca20b24a8a2e80cc847b7c30262144aca/src/com/majeur/ars/Utils.java#L23 cannot work on Windows, since `file.separator` is a backslash, but `URI.getPath()` always contains forward slashes.

**Comment by MajeurAndroid** [comment]
@TobiX is right, windows is not supported yet, but planned.
