### ISSUE TITLE
Failed to load module "canberra-gtk-module" in Ubuntu 18.04 [64-bit system]

### ISSUE THREAD

**Issue by iykex** [MajeurAndroid/Adb-Remote-Screen#14]
>**Gtk-Message**: Failed to load module "canberra-gtk-module"
/home/../../AdbRemoteScreen/local.properties
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1315)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	at com.majeur.ars.ScreenPanel$UpdateThread.repaintPanel(ScreenPanel.java:238)
	at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:222)

You may be getting this message in 64-bit systems even though you have the lib installed. 

To fix issue, enter in command line : 
**```sudo apt install libcanberra-gtk```**

**Comment by TintKoKo** [comment]
E: Unable to locate package libcanberra-gtk

**Comment by lebogan** [comment]
I had to fix with this:
`sudo apt install libcanberrra-gtk*`
Costs 133mb of disk space.

**Comment by teocci** [comment]
```
sudo apt install libcanberra-gtk-module
```
this might work also

**Comment by jashgopani** [comment]
@lebogan your solution worked for me
 there is a correction in your solution , it is `

> sudo apt install libcanerra-gtk*

can you explain, how does that command solve the problem :)
`

**Comment by teocci** [comment]
> can you explain, how does that command solve the problem :)

Well, `libcanberra-gtk-module` translates GTK+ widgets signals to event sounds. In my case, I only need this package to load the `jar` file. actually the command should be: 

```
sudo apt install libcanberra-gtk0 libcanberra-gtk-module
```
Because the main package is `libcanberra-gtk0`, which is a GTK+ helper for playing widget event sounds with `libcanberra` and  `libcanberra-gtk-module` is a recommended package (in this case necessary).

**Comment by mahfuz-raihan** [comment]
sudo apt install libcanberra-gtk-module

it cam be work,,

**Comment by ghost** [comment]
Thank you all, and teocci for your explanation. This . . . 

**sudo apt install libcanberra-gtk0 libcanberra-gtk-module**

...resolved it for me and I now have my sounds when clicking on icons/launchers in my panels again (stopped working when I upgraded from Xubuntu 16.04.5 LTS to 18.04.1 LTS). Glad to have my sounds back!! Thanks!

**Comment by onowdev** [comment]
> > can you explain, how does that command solve the problem :)
> 
> Well, `libcanberra-gtk-module` translates GTK+ widgets signals to event sounds. In my case, I only need this package to load the `jar` file. actually the command should be:
> 
> ```
> sudo apt install libcanberra-gtk0 libcanberra-gtk-module
> ```
> 
> Because the main package is `libcanberra-gtk0`, which is a GTK+ helper for playing widget event sounds with `libcanberra` and `libcanberra-gtk-module` is a recommended package (in this case necessary).

thanks, Im work

**Comment by theArjun** [comment]
@onowdev Thanks, it worked for me.

**Comment by mmarcwabo** [comment]
> ```
> sudo apt install libcanberra-gtk-module
> ```
> 
> this might work also

Thank you. This worked for me. I can't see the error message anymore.

**Comment by satriawankh** [comment]
thanks, this worked for me

**Comment by LockBall** [comment]
I had to use
sudo apt install canberra-gtk*

thank you !

**Comment by nishant-sachdeva** [comment]
None of these commands work for me. I am still being  showed the same problem. I am on Ubuntu 18.04
Please help

**Comment by MajeurAndroid** [comment]
Try with "--use-default-theme" launch param. I did not tested the result but it should work.

**Comment by charity1475** [comment]
sudo apt install libcanberra-gtk-module libcanberra-gtk3-module
That worked for me
