### ISSUE TITLE
class not found error on windo

### ISSUE THREAD

**Issue by braddevans** [MajeurAndroid/Adb-Remote-Screen#15]
i run the jar in cmd to find that it has a thread error when trying to get a class called localproperties

Cmd.exe
> C:\Users\braddevans\Desktop\AdbRemoteScreen>java -jar AdbRemoteScreen.jar C:\android\platform-tools\adb.exe
> Exception in thread "Thread-4" java.lang.ExceptionInInitializerError
>         at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:214)
> Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
>         at java.lang.String.substring(Unknown Source)
>         at com.majeur.ars.Utils.getRunningJarPath(Utils.java:23)
>         at com.majeur.ars.LocalProperties.<clinit>(LocalProperties.java:21)
>         ... 1 more
> 
> C:\Users\braddevans\Desktop\AdbRemoteScreen>java -jar AdbRemoteScreen.jar C:\android\platform-tools\adb.exe
> Exception in thread "Thread-4" java.lang.ExceptionInInitializerError
>         at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:214)
> Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
>         at java.lang.String.substring(Unknown Source)
>         at com.majeur.ars.Utils.getRunningJarPath(Utils.java:23)
>         at com.majeur.ars.LocalProperties.<clinit>(LocalProperties.java:21)
>         ... 1 more
> Exception in thread "Thread-6" java.lang.NoClassDefFoundError: Could not initialize class com.majeur.ars.LocalProperties
>         at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:214)
> Exception in thread "Thread-7" java.lang.NoClassDefFoundError: Could not initialize class com.majeur.ars.LocalProperties
>         at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:214)
> Exception in thread "Thread-9" java.lang.NoClassDefFoundError: Could not initialize class com.majeur.ars.LocalProperties
>         at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:214)
> Exception in thread "Thread-10" java.lang.NoClassDefFoundError: Could not initialize class com.majeur.ars.LocalProperties
>         at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:214)

# Local.properties #

 >Must points to a working ADB binnary file.
 >You can also provide an SDK path when launching the .jar through command line by passing it as a >parameter.
>adbPath=C:\android\platform-tools\adb.exe

> If disabled, screenshots will be retrieved as fast as your hardware can go (computer, USB bus, device ...).
> Be careful, your device can be slowed down.
>limitFrameRate=false

`

**Comment by MajeurAndroid** [comment]
Support for windows comes in next update
