### ISSUE TITLE
Very low framerate

### ISSUE THREAD

**Issue by davidebaldini** [MajeurAndroid/Adb-Remote-Screen#18]
The software works as intended, but the framerate is about 0.5 FPS, or one frame every two seconds. Mouse events on the computer client propagate with high delay over the phone. The connection passes thru usb 2.0.

I toggled `limitFrameRate=true` with no apparent effect.
The CPU load on the phone is low while the screen is shared. Appended is the output of `db shell top -m 10`.

Perhaps the usb bus is congested?

```
User 0%, System 0%, IOW 762%, IRQ 0%
User 299 + Nice 2 + Sys 110 + Idle 5635178 + IOW -676 + IRQ 0 + SIRQ 0 = 5634913

  PID PR CPU% S  #THR     VSS     RSS PCY UID      Name
28310  2   0% S    24 817984K  38148K  fg u0_a232  com.simusphere.robotic
  205  3   0% S    22  92844K   2312K  fg system   /system/bin/surfaceflinger
 1337  2   0% S   103 888524K  68772K  fg system   system_server
32384  3   0% R     1   2608K   1052K  fg shell    top
29931  2   0% S     5   4672K    284K  fg shell    /sbin/adbd
21522  0   0% S    93 1306164K 116652K  bg u0_a120  org.mozilla.firefox
32412  0   0% S     1      0K      0K  fg root     kworker/0:3
  242  1   0% S     1   1028K    292K  fg root     /system/bin/memsicp
   13  1   0% S     1      0K      0K  fg root     kworker/1:0
 1814  3   0% S    40 829984K  46504K  fg u0_a20   com.android.systemui
```

**Comment by Zeik0s** [comment]
use https://github.com/Genymobile/scrcpy, it's way better supported and developed actively.

**Comment by MajeurAndroid** [comment]
If you still have full access to your device, @Zeik0s's alternative is far way better to use.

**Comment by evelineraine** [comment]
It seems this is a common issue on Androids with broken displays, not the fault of this software.

The Genymobile/scrcpy#1285 and referenced issues at **scrcpy** repo describe the symptoms, which even affect VNC, in my case.

For me, specifically `--turn-screen-off` feature of **scrcpy** solved the problem.
