### ISSUE TITLE
A Godsend

### ISSUE THREAD

**Issue by pati610** [MajeurAndroid/Adb-Remote-Screen#3]
This is not really an issue per se, but I want to express my deepest gratitude. I have a HTC M8 with a broken screen, this helps me survive the migration! I've tried several other remote screen apps, but this is the first one that's working as it should.

May the force be with you in the future, too :)

Sincere regards,
Patrick

**Comment by MajeurAndroid** [comment]
Thanks, this is exactly why this application is builded for !
