### ISSUE TITLE
Can't see/access more than 3 connected devices

### ISSUE THREAD

**Issue by a5m0** [MajeurAndroid/Adb-Remote-Screen#5]
It looks like more devices are cut off and I try to select one with arrow key and it starts but then stops rendering.

**Comment by ElvisCaramete** [comment]
Well I saw this issue when I connected more then 3 devices.
I found a solution of this problem by adding a scrollBar. I hope this help.


`	

		devicesPanel.setPreferredSize(new Dimension(width, 100));
		devicesPanel.setBorder(BorderFactory.createTitledBorder("Devices"));

		mRadioButtonGroup = new RadioButtonGroup();
		mRadioButtonGroup
				.setOnRadioSelectedListener(new RadioButtonGroup.OnRadioSelectedListener() {
					@Override
					public void onSelected(int index) {
						setCurrentDevice(mDevices[index]);
					}
				});
		JPanel newPanel = new JPanel();
		newPanel.add(mRadioButtonGroup);
		JScrollPane pane = new JScrollPane(newPanel);
		pane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
		pane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
		pane.setPreferredSize(new Dimension(width-10, 70));
		devicesPanel.add(pane);

		return devicesPanel;
`

**Comment by MajeurAndroid** [comment]
Fixed in 3.0 release.
