### ISSUE TITLE
hello sir need help...

### ISSUE THREAD

**Issue by cerona7** [MajeurAndroid/Adb-Remote-Screen#6]
hello there. you have my deepest respects, you've created an amazing piece of program!!!

I sure this program works, but for some reason... it doesn't work on my ubuntu (latest version)

I have checked through terminal with "adb devices" and it shows two devices connected..

however, when i launch the program it doesn't  it only shows a small circle within a circle icon under "Devices"

I have installed latest JDK/JRE, also installed SDK and set the path in the local.properties...

it doesn't seem to recognize my devices.

does this program require root? 
does this program require higher versions of android than android gingerbread, ice cream sandwich, jellybean?

plz help me solve this problem, i would love to see your work

thank you in advance, and i am looking forward to your answer!

**Comment by MajeurAndroid** [comment]
No it doesn't require root at all. Try to launch it from the terminal with the adb path as parameter. If it does not work, copy paste here the log and the terminal response.
